// Sitemap lines: the address a crawler is sent to for the list of pages, and
// the four ways that address can point somewhere the crawler will not follow,
// will reach twice, or will only read for somebody else.

import type { Doc } from '../../lib/docs.ts';

export const SITEMAP: Record<string, Doc> = {
  'sitemap.protocolMismatch': {
    title: 'The sitemap is listed as http while the site runs on https',
    summary: 'Every fetch of the sitemap hits a redirect, or an insecure copy of the file, because the Sitemap line names a protocol the site has left behind.',
    what: 'sus.bot compares the scheme in the Sitemap line with the scheme the file was read over. This fires when the site answers on https and the line says http, and the finding prints the line to write instead. The check needs a site address, so pasted text on its own is only checked for repeated lines.',
    why: 'If the http address redirects, every fetch costs a round trip and the line disagrees with the URLs inside the sitemap, which are https. If it does not redirect, crawlers read a sitemap served over a protocol the site no longer supports, and what happens to the URLs in it is then up to the crawler.',
    fix: 'Change http to https in the Sitemap line, so that it matches both the site and the URLs listed inside the file. While you are there, check that the sitemap really answers on https, and that every URL in it is written with the same scheme and host the site serves.',
    example: {
      wrong: 'Sitemap: http://www.example.com/sitemap.xml',
      right: 'Sitemap: https://www.example.com/sitemap.xml',
    },
    also: ['sitemap.httpsOnHttp', 'sitemap.crossDomain'],
  },
  'sitemap.httpsOnHttp': {
    title: 'The sitemap is listed as https while the file was read over http',
    summary: 'Crawlers fetch the sitemap over https, which is right if the site redirects there and wrong if http is all it serves.',
    what: 'The robots.txt sus.bot read was served over http, and the Sitemap line names an https address. One file cannot say whether the site answers on https as well, so this is reported as something to confirm rather than as a mistake. Crawlers take the address as written and fetch it over https.',
    why: 'Most of the time it means the site has moved to https and this http copy is what was left behind, in which case there is nothing to lose. If https is not fully served, crawlers meet a certificate error or another site on the way to the sitemap, and the pages it lists are not submitted at all.',
    fix: 'Open the https address of the site and see what answers. If it serves the site, redirect http to https everywhere and the Sitemap line is already right. If it does not, list the sitemap with http until it does, and put the certificate on the list of work to finish.',
    example: {
      wrong: '# the site answers on http only\nSitemap: https://www.example.com/sitemap.xml',
      right: '# the site answers on http only\nSitemap: http://www.example.com/sitemap.xml',
    },
    also: ['sitemap.protocolMismatch', 'fetch.warn.redirectSameSite'],
  },
  'sitemap.crossDomain': {
    title: 'A sitemap on another domain is only read when both sites are verified',
    summary: 'The Sitemap line points at a different domain, and Google reads it only when one Search Console account owns both sites.',
    what: 'sus.bot compares the root domain in the Sitemap line with the domain the file was read from, ignoring www, so www.example.com and example.com count as the same site. This fires when the two differ, which usually means the sitemap is generated by a hosted tool or served from an asset domain.',
    why: 'Cross-site submission exists and it needs both properties verified by the same owner in Search Console. Without that the sitemap is ignored, and every URL that is in it and in no other sitemap is left to be found by links alone. On a large site that is the deep catalogue and everything new.',
    fix: 'Serve the sitemap from the domain the site runs on, at /sitemap.xml, even if that address only proxies or redirects to where the file is generated. If it has to stay on the other domain, verify both in Search Console, and check the verification again whenever either domain changes hands.',
    example: {
      wrong: 'Sitemap: https://sitemaps.example-tool.net/example-com/sitemap.xml',
      right: 'Sitemap: https://www.example.com/sitemap.xml',
    },
    also: ['sitemap.otherSubdomain', 'sitemap.protocolMismatch'],
  },
  'sitemap.otherSubdomain': {
    title: 'The sitemap sits on another host of the same domain',
    summary: 'Crawlers accept it, and the line in robots.txt is what lets a file on that host list the URLs of this one.',
    what: 'The Sitemap line names a host with the same root domain as the site and a different name in front of it, static or cdn for instance. sus.bot reports it so that the line is not taken for a mistake: the file is read, and listing it here is what allows it to hold URLs of the site this robots.txt belongs to.',
    why: 'There is nothing to repair. What there is to know is the dependency. The sitemap covers this site only while the line stays in robots.txt, so a rewrite of the file that drops it leaves the sitemap working for its own host and covering nothing here. The other host also has to stay reachable, with a certificate that matches its name.',
    fix: 'Keep the line. If the sitemap moves, move the line in the same change, because this file is the only thing connecting the two. Check that the other host answers on the protocol the line names, then confirm in Search Console that the sitemap is being read.',
    example: {
      right: 'Sitemap: https://static.example.com/sitemaps/example-com.xml',
    },
    also: ['sitemap.crossDomain', 'sitemap.duplicate'],
  },
  'sitemap.duplicate': {
    title: 'The same sitemap is listed twice',
    summary: 'Two Sitemap lines point at the same address, so the second one adds nothing.',
    what: 'sus.bot parses every Sitemap line and compares the results, so two lines that differ only in the case of the hostname or in a port that is the default count as the same file. The later line is reported with the number of the line that listed it first. A Sitemap line that is not a full address is reported by the parser instead.',
    why: 'Crawlers are not troubled by it. The reason to care is what a repeat says about who writes the file: a plugin and a person, or two plugins, each adding a line of their own. The next change is then made in one of the two places, and in a list with repeats in it a sitemap that is missing is hard to see.',
    fix: 'Keep one line per sitemap. Where there are many, list a single sitemap index and let it name the children, which keeps robots.txt short and moves the list into a generated file. Find out which system writes each line before deleting one, so that it does not come back on the next deploy.',
    example: {
      wrong: 'Sitemap: https://www.example.com/sitemap.xml\nSitemap: https://www.example.com/sitemap-news.xml\nSitemap: https://www.example.com/sitemap.xml',
      right: 'Sitemap: https://www.example.com/sitemap.xml\nSitemap: https://www.example.com/sitemap-news.xml',
    },
    also: ['seo.duplicate', 'parser.sitemapInvalid'],
  },
};
